apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  namespace: sampleapp
spec:
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: sivanesansaravanan/demo-app:test
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  namespace: sampleapp
spec:
  type: NodePort
  selector:
    app: sampleapp
  ports:
  - protocol: TCP
    port: 30082
    targetPort: 80
